[general]
# All fields are required for now
token_size = 64
# Telegram ID of the master account
masterid = 1229057875

[database]
host = "127.0.0.1"
password = "reejitxx"
username = "SpamWatchAPI"
name = "SpamWatchAPI"
